### ISSUE TITLE
How to change the colour of the labels when using gglikert

### ISSUE THREAD

**Issue by Jessiedonny** [larmarange/ggstats#43]
Hi,

I am using the gglikert and found it's a great tool. Thanks for developing it.

Now I need to use some dark colors for the bars so I want to change the colour of the percentage labels from black to white. Is there an easy way to achieve it please? thank you.

**Comment by larmarange** [comment]
I have added additional options in #44 

You can install dev version with `remotes::install_github("larmarange/ggstats#44")`

**Comment by larmarange** [comment]
Do you see anything else? Otherwise, I will release a new version of ggstats
