### ISSUE TITLE
ggstats has been archived

### ISSUE THREAD

**Issue by schloerke** [larmarange/ggstats#49]
The package was archived last week (`2023-11-14`). CRAN is asking for another update in GGally which depends on `{ggstats}`.

Are there plans to get `{ggstats}` unarchived? The package seemed to only fail a test on R-devel, so I don't know why it was actually archived.

```
Check Details
Version: 0.5.0
Check: examples
Result: ERROR
    Running examples in ‘ggstats-Ex.R’ failed
    The error most likely occurred in:
    
    > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
    > ### Name: ggcoef_model
    > ### Title: Plot model coefficients
    > ### Aliases: ggcoef_model ggcoef_table ggcoef_compare ggcoef_multinom
    > ### ggcoef_multicomponents ggcoef_plot
    >
    > ### ** Examples
    >
    > mod <- lm(Sepal.Length ~ Sepal.Width + Species, data = iris)
    > ggcoef_model(mod)
    Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
     conversion failure on 'p ≤ 0.05' in 'mbcsToSbcs': for ≤
    Calls: <Anonymous> ... <Anonymous> -> widthDetails -> widthDetails.text -> grid.Call
    Execution halted
Flavor: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/ggstats-00check.html)
```

Thank you!

**Comment by larmarange** [comment]
Hi @schloerke 

I just discovered it was archived. The notice from CRAN arrived in my Spam box and I did see it. I will explore the bug and try to re-upload it as soon as possible

**Comment by schloerke** [comment]
Thank you so much! The GGally (w/ `{ggstats}` will follow afterwards) 😃

**Comment by larmarange** [comment]
I just made a fix, see #50 

I need to run all the tests. If it's OK I will submit a new version to CRAN tomorrow

**Comment by larmarange** [comment]
submitted to CRAN. Crossing fingers

**Comment by schloerke** [comment]
🤞🤞 Thank you so much!

**Comment by larmarange** [comment]
Back on CRAN 🎉
