### ISSUE TITLE
Question: geom_stripped_cols with dates on the x-axis.

### ISSUE THREAD

**Issue by mooibroekd** [larmarange/ggstats#52]
Hi,

Thanks for your excellent package that has helped me a lot in achieving what I wanted to plot. However, now I am stuck, I cannot get columns when using date as a x-axis, plotting monthly data. What am I doing wrong? I am assuming that plotting monthly data and using a width of 12 would shade each year.

``` r
library(openair)
library(ggstats)
library(ggplot2)

mydata <- openair::mydata

mydata |>
  openair::timeAverage(avg.time = "month") |> 
  ggplot2::ggplot(aes(date, nox)) +   
  ggplot2::geom_point() +   
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggstats::geom_stripped_cols(width = 12)
```

![](https://i.imgur.com/66Uj3E5.png)

<sup>Created on 2023-12-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
Hi,

your `date` column is of class `"POSIXct"`. Therefore, it is internally stored as seconds. `width` should therefore be expressed in seconds.

If you convert it into the class `Date`, it will be stored as a number of days.

``` r
library(openair)
library(ggstats)
library(ggplot2)

mydata <- openair::mydata

d <- mydata |>
  openair::timeAverage(avg.time = "month")

class(d$date)
#> [1] "POSIXct" "POSIXt"

d |> 
  ggplot2::ggplot(aes(date, nox)) +   
  ggplot2::geom_point() +   
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggstats::geom_stripped_cols(width = 365*24*60*60)
```

![](https://i.imgur.com/OLorSKk.png)

``` r

d$date2 <- as.Date(d$date)

d |> 
  ggplot2::ggplot(aes(date2, nox)) +   
  ggplot2::geom_point() +   
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggstats::geom_stripped_cols(width = 365)
```

![](https://i.imgur.com/NZ1puN1.png)

<sup>Created on 2023-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
You may need to adjust `nudge_x` if you want to grey full years.

``` r
library(openair)
library(ggstats)
library(ggplot2)

mydata <- openair::mydata

d <- mydata |>
  openair::timeAverage(avg.time = "month")

d$date2 <- as.Date(d$date)

d |> 
  ggplot2::ggplot(aes(date2, nox)) +   
  ggplot2::geom_point() +   
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggstats::geom_stripped_cols(width = 365, nudge_x = 183)
```

![](https://i.imgur.com/Ty851Gv.png)

<sup>Created on 2023-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mooibroekd** [comment]
Great, thank you. The internal storage in seconds slipped my mind.

**Comment by larmarange** [comment]
Finally, for something clearer, you could re express the date in years.

``` r
library(openair)
library(ggstats)
library(ggplot2)

mydata <- openair::mydata

d <- mydata |>
  openair::timeAverage(avg.time = "month")

d$date2 <- lubridate::year(d$date) + (lubridate::month(d$date) - 1) / 12

d |> 
  ggplot2::ggplot(aes(date2, nox)) +   
  ggplot2::geom_point() +   
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggstats::geom_stripped_cols(nudge_x = 0.5)
```

![](https://i.imgur.com/BPG56Pl.png)

<sup>Created on 2023-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
