### ISSUE TITLE
Italic on ggcoef_table

### ISSUE THREAD

**Issue by Ikarobarreto** [larmarange/ggstats#54]
Hey everyone,

I've been using the ggcoef_table function, and I've been asked to italicize partially variable names within it. I've tried a couple of methods like HTML and expressions, but I haven't had any luck. Could someone please assist me? I've provided a reprex below. My aim is to italicize just the word "Variable."

library(ggstats)
dat<-data.frame(x=rnorm(100),y=rnorm(100),w=runif(100),z=runif(100))
mod<-lm(x~y+w+z)
ggcoef_table(mod,colour = NULL,add_reference_rows = F,
                 variable_labels = list(y= "*Variable* Y",
                                        w = "*Variable* W",
                                        z = "*Variable* Z"))

Thanks!

**Comment by larmarange** [comment]
The easiest way would be to use markdown with the `ggtext` package.

``` r
library(ggplot2)
library(ggstats)
dat <- data.frame(x = rnorm(100), y = rnorm(100), w = runif(100), z = runif(100))
mod <- lm(x ~ y + w + z, data = dat)

p <- ggcoef_model(
  mod,
  colour = NULL, add_reference_rows = F,
  variable_labels = list(
    y = "*Variable* Y",
    w = "W: **bold** and *italic*",
    z = "*Variable* Z"
  )
)

p
```

![](https://i.imgur.com/ypz5c5x.png)

``` r

library(ggtext)
p + theme(strip.text.y.left = element_markdown())
```

![](https://i.imgur.com/9rYy1WY.png)

``` r
p + theme(strip.text.y.left = element_markdown(face = "plain"))
```

![](https://i.imgur.com/2Dbuzlf.png)

``` r

pt <- ggcoef_table(
  mod,
  colour = NULL, add_reference_rows = F,
  variable_labels = list(
    y = "*Variable* Y",
    w = "W: **bold** and *italic*",
    z = "*Variable* Z"
  )
)

pt
```

![](https://i.imgur.com/X39W6qw.png)

``` r

pt[[1]] <- pt[[1]] + theme(strip.text.y.left = element_markdown())
pt
```

![](https://i.imgur.com/aYavpxJ.png)

<sup>Created on 2024-02-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
