### ISSUE TITLE
Query on R 4.2 requirement

### ISSUE THREAD

**Issue by dannyparsons** [larmarange/ggstats#72]
Hi, the latest version of the `ggstats` required R 4.2. Looking at the commit history this seems to be because of the use of the new pipe `|>` feature that has recently been added to base R. This was introduced in R 4.1.0 so I was wondering why the requirement is R 4.2?

The reason for asking is that R 4.1.3 is the last version of R that supports 32 bit Windows, and I use this package as part of a Windows application that uses R with both 32 and 64 bit versions. 

So as of this latest version of `ggstats` we're unable to support 32 bit Windows machines. If `ggstats` could work equally well with an R 4.1 requirement that would greatly help me and any 32 bit Windows users continue to use this really useful package! 
I may have misunderstood the reasoning on this and it's not possible, but I would appreciate your thoughts! Thanks.

**Comment by larmarange** [comment]
Hi. I choose R 4.2 because this the version who introduced the placeholder.

Checking the current code, the placeholder is not used, so I could modify the min version for 4.1 in the next release

**Comment by dannyparsons** [comment]
Thanks very much, this will be great.

**Comment by larmarange** [comment]
You could try the dev version of ggstats, before the next release

**Comment by dannyparsons** [comment]
Thanks, I successfully installed the dev version on R 4.1.0.
