### ISSUE TITLE
How can I change the color of independent variables in ggcoef_table()?

### ISSUE THREAD

**Issue by jgires** [larmarange/ggstats#79]
Hello,

Many thanks for this package, which makes it much easier to read the results of a regression!

I have a question about `ggcoef_table()`. I'm trying to change the color of the dots so that the color is different for each independent variable. It seems to work with `ggcoef_model()`, but not with `ggcoef_table()`.

Is there a way to do this?

Have a nice day,

Joël Girès

**Comment by larmarange** [comment]
Sorry but I'm not sure to understand your question. By default, for ggcoef_table(), the colour is different for each variable. 

Would you have a reproductible example?

**Comment by jgires** [comment]
Sorry, my question was not clear.

I want to use an other palette, by adding `scale_colour_manual(values = c(col1, col2, ...))` to the graph created by ggcoef_table(). But it doesn't work.

**Comment by larmarange** [comment]
`ggcoef_table()` return a patchwork object with 2 plots. You can modifiy each of them. See example.

``` r
library(ggstats)
library(ggplot2)

mod <- lm(Sepal.Length ~ Sepal.Width + Species, data = iris)

p <- ggcoef_table(mod)
p
```

![](https://i.imgur.com/ZxblFgO.png)

``` r

class(p)
#> [1] "patchwork" "gg"        "ggplot"

p[[1]] <- p[[1]] + scale_color_brewer()
#> Scale for colour is already present.
#> Adding another scale for colour, which will replace the existing scale.
p
```

![](https://i.imgur.com/0kb0qpF.png)

<sup>Created on 2024-12-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by jgires** [comment]
Thanks a lot, I didn't know that this graph was made with patchwork !
Merry Christmas :)
